-- Keyword Competition Analyzer: Supabase database setup
-- Run this entire file once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  daily_limit integer not null default 20 check (daily_limit between 0 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx
  on public.profiles (lower(email));

create table if not exists public.daily_usage (
  user_id uuid not null references public.profiles(id) on delete cascade,
  usage_date date not null,
  used_count integer not null default 0 check (used_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null default 'google' check (platform in ('google', 'youtube', 'etsy', 'amazon', 'ebay')),
  research_goal text not null default 'Balanced keyword ideas',
  keyword text not null,
  country text not null,
  language text not null,
  competition_score integer check (competition_score between 0 and 100),
  competition_label text,
  search_intent text,
  result_count integer not null default 0,
  result_snapshot jsonb not null default '{}'::jsonb,
  searched_at timestamptz not null default now()
);

create index if not exists search_history_user_date_idx
  on public.search_history (user_id, searched_at desc);
create index if not exists search_history_platform_idx
  on public.search_history (platform, searched_at desc);
create index if not exists search_history_date_idx
  on public.search_history (searched_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists daily_usage_set_updated_at on public.daily_usage;
create trigger daily_usage_set_updated_at
before update on public.daily_usage
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = case
          when public.profiles.full_name = '' then excluded.full_name
          else public.profiles.full_name
        end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.handle_auth_user_updated()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set email = coalesce(new.email, email),
      full_name = case
        when coalesce(new.raw_user_meta_data ->> 'full_name', '') <> ''
          then new.raw_user_meta_data ->> 'full_name'
        else full_name
      end
  where id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
after update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_auth_user_updated();

-- Atomically reserves one search for the signed-in user.
create or replace function public.reserve_keyword_search()
returns table (
  allowed boolean,
  used_count integer,
  daily_limit integer,
  remaining integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_usage_date date := (now() at time zone 'Asia/Karachi')::date;
  v_limit integer;
  v_used integer;
  v_status text;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select p.daily_limit, p.status
    into v_limit, v_status
  from public.profiles p
  where p.id = v_user_id
  for update;

  if not found then
    return query select false, 0, 20, 20;
    return;
  end if;

  insert into public.daily_usage (user_id, usage_date, used_count)
  values (v_user_id, v_usage_date, 0)
  on conflict (user_id, usage_date) do nothing;

  select d.used_count
    into v_used
  from public.daily_usage d
  where d.user_id = v_user_id and d.usage_date = v_usage_date
  for update;

  if v_status <> 'active' or v_used >= v_limit then
    return query select false, v_used, v_limit, greatest(v_limit - v_used, 0);
    return;
  end if;

  update public.daily_usage d
  set used_count = d.used_count + 1
  where d.user_id = v_user_id and d.usage_date = v_usage_date
  returning d.used_count into v_used;

  return query select true, v_used, v_limit, greatest(v_limit - v_used, 0);
end;
$$;

-- Server-only rollback when Gemini or page analysis fails.
create or replace function public.release_keyword_search(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage_date date := (now() at time zone 'Asia/Karachi')::date;
begin
  update public.daily_usage
  set used_count = greatest(used_count - 1, 0)
  where user_id = p_user_id and usage_date = v_usage_date;
end;
$$;

alter table public.profiles enable row level security;
alter table public.daily_usage enable row level security;
alter table public.search_history enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists daily_usage_select_own on public.daily_usage;
create policy daily_usage_select_own
on public.daily_usage for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists search_history_select_own on public.search_history;
create policy search_history_select_own
on public.search_history for select
to authenticated
using ((select auth.uid()) = user_id);

revoke all on function public.reserve_keyword_search() from public, anon;
grant execute on function public.reserve_keyword_search() to authenticated;

revoke all on function public.release_keyword_search(uuid) from public, anon, authenticated;
grant execute on function public.release_keyword_search(uuid) to service_role;

-- Service-role access is used only inside Netlify Functions.
grant all on public.profiles to service_role;
grant all on public.daily_usage to service_role;
grant all on public.search_history to service_role;
grant usage, select on sequence public.search_history_id_seq to service_role;
